export default {
    SERVICEITEM: [{value: "1", label: "洗头"},
        {value: "2", label: "剪发"},
        {value: "3", label: "烫发"},
        {value: "4", label: "染发"},
        {value: "5", label: "洗剪吹"}],
    WORKMANS: [{value: "2", label: "张三"},
        {value: "2", label: "李四"},
        {value: "3", label: "王五"},
        {value: "4", label: "贾六"},
        {value: "5", label: "王八"}],
    GUESTCOMES: [{value: "1", label: "熟人介绍"},
        {value: "2", label: "路过看到"},
        {value: "3", label: "听说"},
        {value: "4", label: "传单"},
        {value: "5", label: "广告"}],
    COMMODITYS:[{value: "1", label: "霸王洗发水"},
        {value: "2", label: "飘柔洗发水"},
        {value: "3", label: "海飞丝洗发水"},
        {value: "4", label: "染发剂"},
        {value: "5", label: "生发剂"}],
    VIPTYPES:[{value: "1", label: "普通会员"},
        {value: "2", label: "黄金会员"},
        {value: "3", label: "白金会员"},
        {value: "4", label: "钻石会员"}],
    CURRENCYTYPE:[{value: "1", label: "项目消费"},
        {value: "2", label: "商品销售"},
        {value: "3", label: "会员充值"},
        {value: "4", label: "会员开卡"},
        {value: "5", label: "订购套餐"}
    ],
}


